certificate_no = input ("certificate no")
client_name = input("client name")
auditor_name = input("auditor name")
standard = input("standard")
issue_date = input("issue date")
expiry_date = input("expiry date")
print("Certificate no : " + certificate_no)
print("Client Name : " + client_name)
print("Auditor Name : " + auditor_name)
print("Standard : " + standard)
print("Issue Date : " + issue_date)
print("Expiry Date : " + expiry_date)