print("Hello Disha")
print("Hello MScert")
print("The audit pack is subjected to technical review")
print("Certificate is to be granted after passing the technical review")
print("Software: Certification Manager , Technical review , although I have tried to put form fillup for f06 but it couldn't be done however the R01 IS MADE")
print("Application form then contract review then f66 aproval then f17 then audit plan")
print ("the application form to be filled by client, sometimes we filled that along with the contract review but contract & acceptance has to be signed by client")
print("1+2=3 , 300/100 = 3")
print("MS CERT OVERSEAS ")
print("1X2X3 = 6 ; Mdays @ 100 = 600")
print("IAF CODE MD 5:2023 , IAF MD 11 : 2023")
print("iaf code mdf 456")
print("05.08.2026-Certification Manager-Sudipta Das-MS Certification Services Private Limited")
print("accreditation audit went well in between 26.07.2026-29.07.2026")
print("26.07.2026-29.07.2026 accreditation audit done by Ramesh Ramachandran & Poonam Gupta")
print("IAS Surveillance audit 26.07.2026-31.07.2026")
print("Office = 7")
print("45")
print("05.08.2026")
print("Sudipta Das")